export { GetIllustrationLogicQuestionResponse } from './getIllustrationLogicQuestionResponse';
export { GetNumberLinkQuestionResponse } from './getNumberLinkQuestionResponse';
export { GetOneStrokeWritingQuestionResponse } from './getOneStrokeWritingQuestionResponse';
export { PostConnectFourNextRequest } from './postConnectFourNextRequest';
export { PostConnectFourNextResponse } from './postConnectFourNextResponse';
export { PostGomokuNextRequest } from './postGomokuNextRequest';
export { PostGomokuNextResponse } from './postGomokuNextResponse';
export { PostOthelloNextRequest } from './postOthelloNextRequest';
export { PostOthelloNextResponse } from './postOthelloNextResponse';
