import Head from "next/head";

export const Layout = ({ children }: { children: React.ReactNode }): JSX.Element => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mx-auto flex min-h-screen w-full max-w-screen-xl flex-grow p-4">
                <div className="w-full md:py-4 md:px-8">{children}</div>
            </main>
        </>
    );
};
